CREATE DATABASE QL_BAN_HANG
USE  QL_BAN_HANG
CREATE TABLE DANH_MUC
(
	Ma_DM char(10) NOT NULL PRIMARY KEY,
	TEN_DM NVARCHAR(100) NOT NULL unique,
	MO_TA NVARCHAR(200) ,
	TRANG_THAI TINYINT DEFAULT 0,
)

insert into Danh_muc(MA_DM,Ten_dm,mo_ta) values
('QB000002',N'Quần Bò','Tôn Vóc Dáng'),
('QB000003',N'Quần Cộc','Măc Thoáng mát'),
('QB000004',N'Bộ Quần Áo Adidass','Mặc Mát Mẻ');

CREATE TABLE SAN_PHAM
(
	MA_SP CHAR(10) NOT NULL PRIMARY KEY,
	TEN_SP NVARCHAR(200) NOT NULL,
	GIA_NHAP float NOT NULL,
	GIA_BAN float NOT NULL,
	SO_LUONG INT DEFAULT 0,
	GIAM_GIA int DEFAULT 0,
	GHI_CHU NVARCHAR(255) ,
	MA_DM char(10) NOT NULL,
	TRANG_THAI TINYINT DEFAULT 0,
	CONSTRAINT FK_SP_DM FOREIGN KEY (MA_DM) REFERENCES DANH_MUC(MA_DM),
)
insert into San_Pham(Ma_sp , Ten_sp , gia_nhap , gia_ban , So_luong , giam_gia  , ghi_chu , ma_dm)values
('SP0001' , N'Quần Jean ABC', 1200000, 1300000 , 12 , 10, N'đẹp','QB000003'),
('SP0002' , N'Quần Jean DEF', 1200000, 1300000 , 12 , 10  , N'đẹp','QB000002'),
('SP0003' , N'Quần Jean GHI', 1200000, 1300000 , 12 , 10  , N'đẹp','QB000004'),
('SP0004' , N'Quần Jean LMN', 1200000, 1300000 , 12 , 10 , N'đẹp','QB000002');

select * from SAN_PHAM where MA_SP = 'Sp0002';

CREATE TABLE KHACH_HANG
(
	MA_KH INT IDENTITY(1,1) PRIMARY KEY,
	TEN_KH NVARCHAR(55) NOT NULL,
	SDT CHAR(12) NOT NULL,
	DIA_CHI NVARCHAR(100) NOT NULL,
	GIOI_TINH BIT DEFAULT 0,
	NGAY_SINH DATE NOT NULL,
)

CREATE TABLE NHAN_VIEN
(
	MA_NV INT IDENTITY(1,1) PRIMARY KEY,
	TEN_NV NVARCHAR(55) NOT NULL,
	SDT CHAR(12) NOT NULL,
	DIA_CHI NVARCHAR(100) NOT NULL,
	GIOI_TINH BIT DEFAULT 0,
	NGAY_VL DATETIME ,
	EMAIL CHAR(100) NOT NULL,
	TAI_KHOAN NVARCHAR(50) NOT NULL,
	MAT_KHAU NVARCHAR(50) NOT NULL,
	CHUC_VU TINYINT DEFAULT 0,
	TRANG_THAI TINYINT DEFAULT 0,

)
CREATE TABLE HOA_DON(
	MA_HD INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	MA_NV INT NOT NULL,
	NGAY_BAN DATETIME NOT NULL,
	MA_KH INT NOT NULL,
	TONG_TIEN FLOAT NOT NULL,
	CONSTRAINT FK_HD_NV FOREIGN KEY (MA_NV) REFERENCES NHAN_VIEN(MA_NV),
	CONSTRAINT FK_HD_KH FOREIGN KEY (MA_KH) REFERENCES KHACH_HANG(MA_KH),
)

CREATE TABLE CT_HOA_DON (
	MA_CTHD INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	MA_SP CHAR(10) NOT NULL ,
	SO_LUONG INT NOT NULL,
	GIA_BAN FLOAT NOT NULL,
	THANH_TIEN FLOAT NOT NULL, 
	GIAM_GIA FLOAT NOT NULL,
	MA_HD INT NOT NULL ,
	CONSTRAINT FK_HD_CTHD FOREIGN KEY (MA_HD) REFERENCES HOA_DON(MA_HD),
	CONSTRAINT FK_CTHD_SP FOREIGN KEY (MA_SP) REFERENCES SAN_PHAM(MA_SP),
)


CREATE PROC GET_ALL_DANH_MUC
AS 
BEGIN
	SELECT Ma_DM,TEN_DM,MO_TA FROM DANH_MUC
END


CREATE PROC GET_ALL_SAN_PHAM
AS
BEGIN
	SELECT SAN_PHAM.MA_SP , SAN_PHAM.TEN_SP , SAN_PHAM.SO_LUONG,SAN_PHAM.GIA_NHAP,SAN_PHAM.GIA_BAN ,SAN_PHAM.GIAM_GIA , SAN_PHAM.GHI_CHU ,SAN_PHAM.MA_DM,DANH_MUC.TEN_DM 
	FROM SAN_PHAM INNER JOIN DANH_MUC ON SAN_PHAM.MA_DM = DANH_MUC.Ma_DM WHERE SAN_PHAM.TRANG_THAI = 0;
END


CREATE PROC GET_ALL_KHACH_HANG
AS
BEGIN
	SELECT MA_KH,TEN_KH,SDT,KHACH_HANG.GIOI_TINH,KHACH_HANG.DIA_CHI,KHACH_HANG.NGAY_SINH FROM KHACH_HANG
END


CREATE PROC GET_ALL_USER 
AS
BEGIN
	SELECT NHAN_VIEN.MA_NV,NHAN_VIEN.TEN_NV,NHAN_VIEN.GIOI_TINH,NHAN_VIEN.DIA_CHI,NHAN_VIEN.EMAIL,NHAN_VIEN.NGAY_VL, NHAN_VIEN.TAI_KHOAN , NHAN_VIEN.MAT_KHAU FROM NHAN_VIEN
END


CREATE PROC UPDATE_DANH_MUC
	@MA_NV INT ,
	@TEN_NV NVARCHAR(55) ,
	@SDT CHAR(12) ,
	@DIA_CHI NVARCHAR(100),
	@GIOI_TINH BIT ,
	@EMAIL CHAR(100),
	@MAT_KHAU NVARCHAR(50),
	@CHUC_VU TINYINT,
	@TRANG_THAI TINYINT
AS
BEGIN
	UPDATE NHAN_VIEN SET 
		TEN_NV=@TEN_NV,
		SDT = @SDT,
		EMAIL =@EMAIL,
		GIOI_TINH= @GIOI_TINH,
		MAT_KHAU =@MAT_KHAU,
		DIA_CHI =@DIA_CHI,
		CHUC_VU = @CHUC_VU,
		TRANG_THAI = @TRANG_THAI
		WHERE MA_NV=@MA_NV;
END


