CREATE DATABASE QL_BAN_HANG
USE  QL_BAN_HANG
CREATE TABLE DANH_MUC
(
	Ma_DM char(10) NOT NULL PRIMARY KEY,
	TEN_DM NVARCHAR(100) NOT NULL unique,
	MO_TA NVARCHAR(200) ,
	TRANG_THAI TINYINT DEFAULT 0,
)

insert into Danh_muc(MA_DM,Ten_dm,mo_ta) values
('QB000002',N'Quần Bò','Tôn Vóc Dáng'),
('QB000003',N'Quần Cộc','Măc Thoáng mát'),
('QB000004',N'Bộ Quần Áo Adidass','Mặc Mát Mẻ');

CREATE TABLE SAN_PHAM
(
	MA_SP CHAR(10) NOT NULL PRIMARY KEY,
	TEN_SP NVARCHAR(200) NOT NULL,
	GIA_NHAP float NOT NULL,
	GIA_BAN float NOT NULL,
	SO_LUONG INT DEFAULT 0,
	GIAM_GIA int DEFAULT 0,
	GHI_CHU NVARCHAR(255) ,
	MA_DM char(10) NOT NULL,
	TRANG_THAI TINYINT DEFAULT 0,
	CONSTRAINT FK_SP_DM FOREIGN KEY (MA_DM) REFERENCES DANH_MUC(MA_DM),
)
insert into San_Pham(Ma_sp , Ten_sp , gia_nhap , gia_ban , So_luong , giam_gia  , ghi_chu , ma_dm)values
('SP00023' , N'Quần Jean ABC', 1200000, 1300000 , 5 , 10, N'đẹp','QB000003'),
('SP00020' , N'Quần Jean DEF', 1200000, 1300000 , 12 , 10  , N'đẹp','QB000002'),
('SP00021' , N'Quần Jean GHI', 1200000, 1300000 , 12 , 10  , N'đẹp','QB000004'),
('SP00022' , N'Quần Jean LMN', 1200000, 1300000 , 12 , 10 , N'đẹp','QB000002');

select * from SAN_PHAM where MA_SP = 'Sp0002';

CREATE TABLE KHACH_HANG
(
	MA_KH INT IDENTITY(0,1) PRIMARY KEY,
	TEN_KH NVARCHAR(55) NOT NULL,
	SDT CHAR(12) NOT NULL,
	DIA_CHI NVARCHAR(100) NOT NULL,
	GIOI_TINH BIT DEFAULT 0,
	NGAY_SINH DATE NOT NULL,
)
insert into khach_hang(Ten_kh,sdt,dia_chi,gioi_tinh,ngay_Sinh)values('ABC','0123456789','dvdsgvds',0,'02/11/2000')
select * from KHACH_HANG
CREATE TABLE NHAN_VIEN
(
	MA_NV INT IDENTITY(1,1) PRIMARY KEY,
	TEN_NV NVARCHAR(55) NOT NULL,
	SDT CHAR(12) NOT NULL,
	DIA_CHI NVARCHAR(100) NOT NULL,
	GIOI_TINH BIT DEFAULT 0,
	NGAY_VL DATETIME ,
	EMAIL CHAR(100) NOT NULL,
	TAI_KHOAN NVARCHAR(50) NOT NULL,
	MAT_KHAU NVARCHAR(50) NOT NULL,
	CHUC_VU TINYINT DEFAULT 0,
	TRANG_THAI TINYINT DEFAULT 0,

)
CREATE TABLE HOA_DON(
	MA_HD INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	MA_NV INT NOT NULL,
	NGAY_BAN DATETIME NOT NULL,
	MA_KH INT,
	TONG_TIEN FLOAT NOT NULL,
	CONSTRAINT FK_HD_NV FOREIGN KEY (MA_NV) REFERENCES NHAN_VIEN(MA_NV),
	CONSTRAINT FK_HD_KH FOREIGN KEY (MA_KH) REFERENCES KHACH_HANG(MA_KH),
)


CREATE TABLE HOA_DON_NHAP(
	MA_HD_NHAP INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	MA_NV INT NOT NULL,
	NGAY_NHAP DATETIME NOT NULL,
	TONG_TIEN FLOAT NOT NULL,
	CONSTRAINT FK_HDN_NV FOREIGN KEY (MA_NV) REFERENCES NHAN_VIEN(MA_NV),
)
CREATE TABLE CT_HOA_DON_NHAP (
	MA_CTHD_NHAP INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	MA_SP CHAR(10) NOT NULL ,
	GIA_NHAP FLOAT NOT NULL,
	GIAM_GIA FLOAT NOT NULL,
	SO_LUONG INT NOT NULL,
	THANH_TIEN FLOAT NOT NULL, 
	MA_HD_NHAP INT NOT NULL ,
	CONSTRAINT FK_HDN_CTHD FOREIGN KEY (MA_HD_NHAP) REFERENCES HOA_DON_NHAP(MA_HD_NHAP),
	CONSTRAINT FK_CTHD_N_SP FOREIGN KEY (MA_SP) REFERENCES SAN_PHAM(MA_SP),
)

CREATE TABLE CT_HOA_DON (
	MA_CTHD INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	MA_SP CHAR(10) NOT NULL ,
	GIA_BAN FLOAT NOT NULL,
	GIAM_GIA FLOAT NOT NULL,
	SO_LUONG INT NOT NULL,
	THANH_TIEN FLOAT NOT NULL, 
	MA_HD INT NOT NULL ,
	CONSTRAINT FK_HD_CTHD FOREIGN KEY (MA_HD) REFERENCES HOA_DON(MA_HD),
	CONSTRAINT FK_CTHD_SP FOREIGN KEY (MA_SP) REFERENCES SAN_PHAM(MA_SP),
)


CREATE PROC GET_ALL_DANH_MUC
AS 
BEGIN
	SELECT Ma_DM,TEN_DM,MO_TA FROM DANH_MUC
END
GO

CREATE PROC GET_ALL_SAN_PHAM
AS
BEGIN
	SELECT SAN_PHAM.MA_SP , SAN_PHAM.TEN_SP , SAN_PHAM.SO_LUONG,SAN_PHAM.GIA_NHAP,SAN_PHAM.GIA_BAN ,SAN_PHAM.GIAM_GIA , SAN_PHAM.GHI_CHU ,SAN_PHAM.MA_DM,DANH_MUC.TEN_DM 
	FROM SAN_PHAM INNER JOIN DANH_MUC ON SAN_PHAM.MA_DM = DANH_MUC.Ma_DM WHERE SAN_PHAM.TRANG_THAI = 0;
END
GO

CREATE PROC GET_ALL_KHACH_HANG
AS
BEGIN
	SELECT MA_KH,TEN_KH,SDT,KHACH_HANG.GIOI_TINH,KHACH_HANG.DIA_CHI,KHACH_HANG.NGAY_SINH FROM KHACH_HANG
END
GO

CREATE PROC GET_ALL_USER 
AS
BEGIN
	SELECT NHAN_VIEN.MA_NV,NHAN_VIEN.TEN_NV,NHAN_VIEN.GIOI_TINH,NHAN_VIEN.DIA_CHI,NHAN_VIEN.EMAIL,NHAN_VIEN.NGAY_VL, NHAN_VIEN.TAI_KHOAN , NHAN_VIEN.MAT_KHAU FROM NHAN_VIEN
END


CREATE PROC UPDATE_DANH_MUC
	@MA_NV INT ,
	@TEN_NV NVARCHAR(55) ,
	@SDT CHAR(12) ,
	@DIA_CHI NVARCHAR(100),
	@GIOI_TINH BIT ,
	@EMAIL CHAR(100),
	@MAT_KHAU NVARCHAR(50),
	@CHUC_VU TINYINT,
	@TRANG_THAI TINYINT
AS
BEGIN
	UPDATE NHAN_VIEN SET 
		TEN_NV=@TEN_NV,
		SDT = @SDT,
		EMAIL =@EMAIL,
		GIOI_TINH= @GIOI_TINH,
		MAT_KHAU =@MAT_KHAU,
		DIA_CHI =@DIA_CHI,
		CHUC_VU = @CHUC_VU,
		TRANG_THAI = @TRANG_THAI
		WHERE MA_NV=@MA_NV;
END
GO

CREATE PROC PRD_INSERT_CTHD

	@MA_SP CHAR(10) ,
	@SO_LUONG INT ,
	@GIA_BAN FLOAT,
	@THANH_TIEN FLOAT , 
	@GIAM_GIA FLOAT ,
	@MA_HD INT
AS
BEGIN 
	INSERT INTO CT_HOA_DON (MA_SP,MA_HD,GIAM_GIA,GIA_BAN,SO_LUONG,THANH_TIEN)
	VALUES (@MA_SP  ,
	@SO_LUONG  ,
	@GIA_BAN ,
	@THANH_TIEN  , 
	@GIAM_GIA  ,
	@MA_HD
	)
END 
GO

CREATE PROC GETALLHOADON
AS
BEGIN
	SELECT HOA_DON.MA_HD , HOA_DON.MA_KH ,KHACH_HANG.TEN_KH , HOA_DON.NGAY_BAN , HOA_DON.TONG_TIEN , HOA_DON.MA_NV  FROM HOA_DON , KHACH_HANG WHERE HOA_DON.MA_KH = KHACH_HANG.MA_KH
END
GO

CREATE PROC LOC_HOA_DON
@START DATE,
@END DATE
AS
BEGIN
	SELECT HOA_DON.MA_HD , HOA_DON.MA_KH ,KHACH_HANG.TEN_KH , HOA_DON.NGAY_BAN , HOA_DON.TONG_TIEN , HOA_DON.MA_NV  FROM HOA_DON JOIN KHACH_HANG ON HOA_DON.MA_KH = KHACH_HANG.MA_KH
	WHERE @START <= convert(date,HOA_DON.NGAY_BAN) and convert(date,HOA_DON.NGAY_BAN) <=@END; 
END
GO


CREATE PROC GETALLHOADONNHAP
AS
BEGIN
	SELECT HOA_DON_NHAP.MA_HD_NHAP  , HOA_DON_NHAP.NGAY_NHAP , HOA_DON_NHAP.TONG_TIEN , NHAN_VIEN.MA_NV , NHAN_VIEN.TEN_NV FROM HOA_DON_NHAP , NHAN_VIEN WHERE HOA_DON_NHAP.MA_NV = NHAN_VIEN.MA_NV
END
GO


CREATE PROC LOC_HOA_DON_NHAP
@START DATE,
@END DATE
AS
BEGIN
	SELECT HOA_DON_NHAP.MA_HD_NHAP , HOA_DON_NHAP.NGAY_NHAP , HOA_DON_NHAP.TONG_TIEN , HOA_DON_NHAP.MA_NV,NHAN_VIEN.TEN_NV   FROM HOA_DON_NHAP JOIN NHAN_VIEN ON HOA_DON_NHAP.MA_NV = NHAN_VIEN.MA_NV
	WHERE @START <= convert(date,HOA_DON_NHAP.NGAY_NHAP) and convert(date,HOA_DON_NHAP.NGAY_NHAP) <=@END; 
END
GO

CREATE PROC CT_INSERT_HOADONNHAP
	@MA_SP CHAR(10) ,
	@SO_LUONG INT ,
	@GIA_NHAP FLOAT,
	@THANH_TIEN FLOAT , 
	@GIAM_GIA FLOAT ,
	@MA_HD INT
AS 
BEGIN
	INSERT INTO CT_HOA_DON_NHAP(MA_SP,GIA_NHAP,GIAM_GIA,SO_LUONG,THANH_TIEN , MA_HD_NHAP)
	VALUES (
	@MA_SP  ,
	@GIA_NHAP ,
	@GIAM_GIA  ,
	@SO_LUONG  ,
	@THANH_TIEN  ,
	@MA_HD
	)
END

