//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class CT_HOA_DON
    {
        public CT_HOA_DON(string MA_SP , int sl , double gia , double Tong , double giam_gia , int MaHD)
        {
            this.MA_SP = MA_SP;
            this.SO_LUONG = sl;
            this.GIA_BAN = gia;
            this.GIAM_GIA = giam_gia;
            this.THANH_TIEN = Tong;
            this.MA_HD = MaHD;
        }
        public int MA_CTHD { get; set; }
        public string MA_SP { get; set; }
        public int SO_LUONG { get; set; }
        public double GIA_BAN { get; set; }
        public double THANH_TIEN { get; set; }
        public double GIAM_GIA { get; set; }
        public int MA_HD { get; set; }
    
        public virtual SAN_PHAM SAN_PHAM { get; set; }
        public virtual HOA_DON HOA_DON { get; set; }
    }
}
