//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class HOA_DON_NHAP
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HOA_DON_NHAP()
        {
            this.CT_HOA_DON_NHAP = new HashSet<CT_HOA_DON_NHAP>();
        }
    
        public int MA_HD_NHAP { get; set; }
        public string MA_NV { get; set; }
        public System.DateTime NGAY_NHAP { get; set; }
        public double TONG_TIEN { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CT_HOA_DON_NHAP> CT_HOA_DON_NHAP { get; set; }
        public virtual NHAN_VIEN NHAN_VIEN { get; set; }
    }
}
