//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class QL_BAN_HANG : DbContext
    {
        public QL_BAN_HANG()
            : base("name=QL_BAN_HANG")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CT_HOA_DON> CT_HOA_DON { get; set; }
        public virtual DbSet<DANH_MUC> DANH_MUC { get; set; }
        public virtual DbSet<HOA_DON> HOA_DON { get; set; }
        public virtual DbSet<KHACH_HANG> KHACH_HANG { get; set; }
        public virtual DbSet<NHAN_VIEN> NHAN_VIEN { get; set; }
        public virtual DbSet<SAN_PHAM> SAN_PHAM { get; set; }
        public virtual DbSet<CT_HOA_DON_NHAP> CT_HOA_DON_NHAP { get; set; }
        public virtual DbSet<HOA_DON_NHAP> HOA_DON_NHAP { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
    
        public virtual ObjectResult<GET_ALL_DANH_MUC_Result> GET_ALL_DANH_MUC()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GET_ALL_DANH_MUC_Result>("GET_ALL_DANH_MUC");
        }
    
        public virtual ObjectResult<GET_ALL_KHACH_HANG_Result> GET_ALL_KHACH_HANG()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GET_ALL_KHACH_HANG_Result>("GET_ALL_KHACH_HANG");
        }
    
        public virtual ObjectResult<GET_ALL_SAN_PHAM_Result> GET_ALL_SAN_PHAM()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GET_ALL_SAN_PHAM_Result>("GET_ALL_SAN_PHAM");
        }
    
        public virtual ObjectResult<GET_ALL_USER_Result> GET_ALL_USER()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GET_ALL_USER_Result>("GET_ALL_USER");
        }
    
        public virtual int UPDATE_DANH_MUC(Nullable<int> mA_NV, string tEN_NV, string sDT, string dIA_CHI, Nullable<bool> gIOI_TINH, string eMAIL, string mAT_KHAU, Nullable<byte> cHUC_VU, Nullable<byte> tRANG_THAI)
        {
            var mA_NVParameter = mA_NV.HasValue ?
                new ObjectParameter("MA_NV", mA_NV) :
                new ObjectParameter("MA_NV", typeof(int));
    
            var tEN_NVParameter = tEN_NV != null ?
                new ObjectParameter("TEN_NV", tEN_NV) :
                new ObjectParameter("TEN_NV", typeof(string));
    
            var sDTParameter = sDT != null ?
                new ObjectParameter("SDT", sDT) :
                new ObjectParameter("SDT", typeof(string));
    
            var dIA_CHIParameter = dIA_CHI != null ?
                new ObjectParameter("DIA_CHI", dIA_CHI) :
                new ObjectParameter("DIA_CHI", typeof(string));
    
            var gIOI_TINHParameter = gIOI_TINH.HasValue ?
                new ObjectParameter("GIOI_TINH", gIOI_TINH) :
                new ObjectParameter("GIOI_TINH", typeof(bool));
    
            var eMAILParameter = eMAIL != null ?
                new ObjectParameter("EMAIL", eMAIL) :
                new ObjectParameter("EMAIL", typeof(string));
    
            var mAT_KHAUParameter = mAT_KHAU != null ?
                new ObjectParameter("MAT_KHAU", mAT_KHAU) :
                new ObjectParameter("MAT_KHAU", typeof(string));
    
            var cHUC_VUParameter = cHUC_VU.HasValue ?
                new ObjectParameter("CHUC_VU", cHUC_VU) :
                new ObjectParameter("CHUC_VU", typeof(byte));
    
            var tRANG_THAIParameter = tRANG_THAI.HasValue ?
                new ObjectParameter("TRANG_THAI", tRANG_THAI) :
                new ObjectParameter("TRANG_THAI", typeof(byte));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UPDATE_DANH_MUC", mA_NVParameter, tEN_NVParameter, sDTParameter, dIA_CHIParameter, gIOI_TINHParameter, eMAILParameter, mAT_KHAUParameter, cHUC_VUParameter, tRANG_THAIParameter);
        }
    
        public virtual ObjectResult<GETALLHOADON_Result> GETALLHOADON()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GETALLHOADON_Result>("GETALLHOADON");
        }
    
        public virtual ObjectResult<LOC_HOA_DON_Result> LOC_HOA_DON(Nullable<System.DateTime> sTART, Nullable<System.DateTime> eND)
        {
            var sTARTParameter = sTART.HasValue ?
                new ObjectParameter("START", sTART) :
                new ObjectParameter("START", typeof(System.DateTime));
    
            var eNDParameter = eND.HasValue ?
                new ObjectParameter("END", eND) :
                new ObjectParameter("END", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<LOC_HOA_DON_Result>("LOC_HOA_DON", sTARTParameter, eNDParameter);
        }
    
        public virtual int sp_alterdiagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_alterdiagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_creatediagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_creatediagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_dropdiagram(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_dropdiagram", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagramdefinition_Result> sp_helpdiagramdefinition(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagramdefinition_Result>("sp_helpdiagramdefinition", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagrams_Result> sp_helpdiagrams(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagrams_Result>("sp_helpdiagrams", diagramnameParameter, owner_idParameter);
        }
    
        public virtual int sp_renamediagram(string diagramname, Nullable<int> owner_id, string new_diagramname)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var new_diagramnameParameter = new_diagramname != null ?
                new ObjectParameter("new_diagramname", new_diagramname) :
                new ObjectParameter("new_diagramname", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_renamediagram", diagramnameParameter, owner_idParameter, new_diagramnameParameter);
        }
    
        public virtual int sp_upgraddiagrams()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_upgraddiagrams");
        }
    }
}
