//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class QL_BAN_HANG : DbContext
    {
        public QL_BAN_HANG()
            : base("name=QL_BAN_HANG")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CT_HOA_DON> CT_HOA_DON { get; set; }
        public virtual DbSet<CT_HOA_DON_NHAP> CT_HOA_DON_NHAP { get; set; }
        public virtual DbSet<DANH_MUC> DANH_MUC { get; set; }
        public virtual DbSet<HOA_DON> HOA_DON { get; set; }
        public virtual DbSet<HOA_DON_NHAP> HOA_DON_NHAP { get; set; }
        public virtual DbSet<KHACH_HANG> KHACH_HANG { get; set; }
        public virtual DbSet<NHAN_VIEN> NHAN_VIEN { get; set; }
        public virtual DbSet<SAN_PHAM> SAN_PHAM { get; set; }
    
        public virtual int CT_INSERT_HOADONNHAP(string mA_SP, Nullable<int> sO_LUONG, Nullable<double> gIA_NHAP, Nullable<double> tHANH_TIEN, Nullable<double> gIAM_GIA, Nullable<int> mA_HD)
        {
            var mA_SPParameter = mA_SP != null ?
                new ObjectParameter("MA_SP", mA_SP) :
                new ObjectParameter("MA_SP", typeof(string));
    
            var sO_LUONGParameter = sO_LUONG.HasValue ?
                new ObjectParameter("SO_LUONG", sO_LUONG) :
                new ObjectParameter("SO_LUONG", typeof(int));
    
            var gIA_NHAPParameter = gIA_NHAP.HasValue ?
                new ObjectParameter("GIA_NHAP", gIA_NHAP) :
                new ObjectParameter("GIA_NHAP", typeof(double));
    
            var tHANH_TIENParameter = tHANH_TIEN.HasValue ?
                new ObjectParameter("THANH_TIEN", tHANH_TIEN) :
                new ObjectParameter("THANH_TIEN", typeof(double));
    
            var gIAM_GIAParameter = gIAM_GIA.HasValue ?
                new ObjectParameter("GIAM_GIA", gIAM_GIA) :
                new ObjectParameter("GIAM_GIA", typeof(double));
    
            var mA_HDParameter = mA_HD.HasValue ?
                new ObjectParameter("MA_HD", mA_HD) :
                new ObjectParameter("MA_HD", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CT_INSERT_HOADONNHAP", mA_SPParameter, sO_LUONGParameter, gIA_NHAPParameter, tHANH_TIENParameter, gIAM_GIAParameter, mA_HDParameter);
        }
    
        public virtual ObjectResult<GET_ALL_DANH_MUC_Result> GET_ALL_DANH_MUC()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GET_ALL_DANH_MUC_Result>("GET_ALL_DANH_MUC");
        }
    
        public virtual ObjectResult<GET_ALL_KHACHHANG_Result> GET_ALL_KHACHHANG()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GET_ALL_KHACHHANG_Result>("GET_ALL_KHACHHANG");
        }
    
        public virtual ObjectResult<GET_ALL_SAN_PHAM_Result> GET_ALL_SAN_PHAM()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GET_ALL_SAN_PHAM_Result>("GET_ALL_SAN_PHAM");
        }
    
        public virtual ObjectResult<GETALLHOADON_Result> GETALLHOADON(string nv)
        {
            var nvParameter = nv != null ?
                new ObjectParameter("nv", nv) :
                new ObjectParameter("nv", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GETALLHOADON_Result>("GETALLHOADON", nvParameter);
        }
    
        public virtual ObjectResult<GETALLHOADONNHAP_Result> GETALLHOADONNHAP(string manv)
        {
            var manvParameter = manv != null ?
                new ObjectParameter("manv", manv) :
                new ObjectParameter("manv", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GETALLHOADONNHAP_Result>("GETALLHOADONNHAP", manvParameter);
        }
    
        public virtual ObjectResult<LOC_HOA_DON_Result> LOC_HOA_DON(string manv, Nullable<System.DateTime> sTART, Nullable<System.DateTime> eND)
        {
            var manvParameter = manv != null ?
                new ObjectParameter("manv", manv) :
                new ObjectParameter("manv", typeof(string));
    
            var sTARTParameter = sTART.HasValue ?
                new ObjectParameter("START", sTART) :
                new ObjectParameter("START", typeof(System.DateTime));
    
            var eNDParameter = eND.HasValue ?
                new ObjectParameter("END", eND) :
                new ObjectParameter("END", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<LOC_HOA_DON_Result>("LOC_HOA_DON", manvParameter, sTARTParameter, eNDParameter);
        }
    
        public virtual ObjectResult<LOC_HOA_DON_NHAP_Result> LOC_HOA_DON_NHAP(string mANV, Nullable<System.DateTime> sTART, Nullable<System.DateTime> eND)
        {
            var mANVParameter = mANV != null ?
                new ObjectParameter("MANV", mANV) :
                new ObjectParameter("MANV", typeof(string));
    
            var sTARTParameter = sTART.HasValue ?
                new ObjectParameter("START", sTART) :
                new ObjectParameter("START", typeof(System.DateTime));
    
            var eNDParameter = eND.HasValue ?
                new ObjectParameter("END", eND) :
                new ObjectParameter("END", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<LOC_HOA_DON_NHAP_Result>("LOC_HOA_DON_NHAP", mANVParameter, sTARTParameter, eNDParameter);
        }
    
        public virtual int PRD_INSERT_CTHD(string mA_SP, Nullable<int> sO_LUONG, Nullable<double> gIA_BAN, Nullable<double> tHANH_TIEN, Nullable<double> gIAM_GIA, Nullable<int> mA_HD)
        {
            var mA_SPParameter = mA_SP != null ?
                new ObjectParameter("MA_SP", mA_SP) :
                new ObjectParameter("MA_SP", typeof(string));
    
            var sO_LUONGParameter = sO_LUONG.HasValue ?
                new ObjectParameter("SO_LUONG", sO_LUONG) :
                new ObjectParameter("SO_LUONG", typeof(int));
    
            var gIA_BANParameter = gIA_BAN.HasValue ?
                new ObjectParameter("GIA_BAN", gIA_BAN) :
                new ObjectParameter("GIA_BAN", typeof(double));
    
            var tHANH_TIENParameter = tHANH_TIEN.HasValue ?
                new ObjectParameter("THANH_TIEN", tHANH_TIEN) :
                new ObjectParameter("THANH_TIEN", typeof(double));
    
            var gIAM_GIAParameter = gIAM_GIA.HasValue ?
                new ObjectParameter("GIAM_GIA", gIAM_GIA) :
                new ObjectParameter("GIAM_GIA", typeof(double));
    
            var mA_HDParameter = mA_HD.HasValue ?
                new ObjectParameter("MA_HD", mA_HD) :
                new ObjectParameter("MA_HD", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PRD_INSERT_CTHD", mA_SPParameter, sO_LUONGParameter, gIA_BANParameter, tHANH_TIENParameter, gIAM_GIAParameter, mA_HDParameter);
        }
    
        public virtual ObjectResult<SEARCH_KHACH_HANG_Result> SEARCH_KHACH_HANG(string mA_KH, string tEN_KH, string sDT, string dIA_CHI)
        {
            var mA_KHParameter = mA_KH != null ?
                new ObjectParameter("MA_KH", mA_KH) :
                new ObjectParameter("MA_KH", typeof(string));
    
            var tEN_KHParameter = tEN_KH != null ?
                new ObjectParameter("TEN_KH", tEN_KH) :
                new ObjectParameter("TEN_KH", typeof(string));
    
            var sDTParameter = sDT != null ?
                new ObjectParameter("SDT", sDT) :
                new ObjectParameter("SDT", typeof(string));
    
            var dIA_CHIParameter = dIA_CHI != null ?
                new ObjectParameter("DIA_CHI", dIA_CHI) :
                new ObjectParameter("DIA_CHI", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SEARCH_KHACH_HANG_Result>("SEARCH_KHACH_HANG", mA_KHParameter, tEN_KHParameter, sDTParameter, dIA_CHIParameter);
        }
    
        public virtual ObjectResult<GETALLCTHD_BAN_Result> GETALLCTHD_BAN(Nullable<int> ma_hd)
        {
            var ma_hdParameter = ma_hd.HasValue ?
                new ObjectParameter("ma_hd", ma_hd) :
                new ObjectParameter("ma_hd", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GETALLCTHD_BAN_Result>("GETALLCTHD_BAN", ma_hdParameter);
        }
    
        public virtual int DELETE_HOA_DON(Nullable<int> mA_HD)
        {
            var mA_HDParameter = mA_HD.HasValue ?
                new ObjectParameter("MA_HD", mA_HD) :
                new ObjectParameter("MA_HD", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DELETE_HOA_DON", mA_HDParameter);
        }
    
        public virtual ObjectResult<GET_ALL_NHAN_VIEN_Result> GET_ALL_NHAN_VIEN()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GET_ALL_NHAN_VIEN_Result>("GET_ALL_NHAN_VIEN");
        }
    
        public virtual ObjectResult<GETALLCTHD_NHAP_Result> GETALLCTHD_NHAP(Nullable<int> ma_hd)
        {
            var ma_hdParameter = ma_hd.HasValue ?
                new ObjectParameter("ma_hd", ma_hd) :
                new ObjectParameter("ma_hd", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GETALLCTHD_NHAP_Result>("GETALLCTHD_NHAP", ma_hdParameter);
        }
    
        public virtual ObjectResult<SEARCH_NHAN_VIEN_Result> SEARCH_NHAN_VIEN(string mA_NV, string tEN_NV, string sDT, string nGAY_VL, string dIA_CHI, string gIOI_TINH, string eMAIL, string tAI_KHOAN, string cHUC_VU)
        {
            var mA_NVParameter = mA_NV != null ?
                new ObjectParameter("MA_NV", mA_NV) :
                new ObjectParameter("MA_NV", typeof(string));
    
            var tEN_NVParameter = tEN_NV != null ?
                new ObjectParameter("TEN_NV", tEN_NV) :
                new ObjectParameter("TEN_NV", typeof(string));
    
            var sDTParameter = sDT != null ?
                new ObjectParameter("SDT", sDT) :
                new ObjectParameter("SDT", typeof(string));
    
            var nGAY_VLParameter = nGAY_VL != null ?
                new ObjectParameter("NGAY_VL", nGAY_VL) :
                new ObjectParameter("NGAY_VL", typeof(string));
    
            var dIA_CHIParameter = dIA_CHI != null ?
                new ObjectParameter("DIA_CHI", dIA_CHI) :
                new ObjectParameter("DIA_CHI", typeof(string));
    
            var gIOI_TINHParameter = gIOI_TINH != null ?
                new ObjectParameter("GIOI_TINH", gIOI_TINH) :
                new ObjectParameter("GIOI_TINH", typeof(string));
    
            var eMAILParameter = eMAIL != null ?
                new ObjectParameter("EMAIL", eMAIL) :
                new ObjectParameter("EMAIL", typeof(string));
    
            var tAI_KHOANParameter = tAI_KHOAN != null ?
                new ObjectParameter("TAI_KHOAN", tAI_KHOAN) :
                new ObjectParameter("TAI_KHOAN", typeof(string));
    
            var cHUC_VUParameter = cHUC_VU != null ?
                new ObjectParameter("CHUC_VU", cHUC_VU) :
                new ObjectParameter("CHUC_VU", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SEARCH_NHAN_VIEN_Result>("SEARCH_NHAN_VIEN", mA_NVParameter, tEN_NVParameter, sDTParameter, nGAY_VLParameter, dIA_CHIParameter, gIOI_TINHParameter, eMAILParameter, tAI_KHOANParameter, cHUC_VUParameter);
        }
    }
}
