//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class QL_BAN_HANGEntities : DbContext
    {
        public QL_BAN_HANGEntities()
            : base("name=QL_BAN_HANGEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CT_HOA_DON> CT_HOA_DON { get; set; }
        public virtual DbSet<CT_HOA_DON_NHAP> CT_HOA_DON_NHAP { get; set; }
        public virtual DbSet<DANH_MUC> DANH_MUC { get; set; }
        public virtual DbSet<HOA_DON> HOA_DON { get; set; }
        public virtual DbSet<HOA_DON_NHAP> HOA_DON_NHAP { get; set; }
        public virtual DbSet<KHACH_HANG> KHACH_HANG { get; set; }
        public virtual DbSet<NHAN_VIEN> NHAN_VIEN { get; set; }
        public virtual DbSet<SAN_PHAM> SAN_PHAM { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
    
        public virtual int CT_INSERT_HOADONNHAP(string mA_SP, Nullable<int> sO_LUONG, Nullable<double> gIA_NHAP, Nullable<double> tHANH_TIEN, Nullable<double> gIAM_GIA, Nullable<int> mA_HD)
        {
            var mA_SPParameter = mA_SP != null ?
                new ObjectParameter("MA_SP", mA_SP) :
                new ObjectParameter("MA_SP", typeof(string));
    
            var sO_LUONGParameter = sO_LUONG.HasValue ?
                new ObjectParameter("SO_LUONG", sO_LUONG) :
                new ObjectParameter("SO_LUONG", typeof(int));
    
            var gIA_NHAPParameter = gIA_NHAP.HasValue ?
                new ObjectParameter("GIA_NHAP", gIA_NHAP) :
                new ObjectParameter("GIA_NHAP", typeof(double));
    
            var tHANH_TIENParameter = tHANH_TIEN.HasValue ?
                new ObjectParameter("THANH_TIEN", tHANH_TIEN) :
                new ObjectParameter("THANH_TIEN", typeof(double));
    
            var gIAM_GIAParameter = gIAM_GIA.HasValue ?
                new ObjectParameter("GIAM_GIA", gIAM_GIA) :
                new ObjectParameter("GIAM_GIA", typeof(double));
    
            var mA_HDParameter = mA_HD.HasValue ?
                new ObjectParameter("MA_HD", mA_HD) :
                new ObjectParameter("MA_HD", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CT_INSERT_HOADONNHAP", mA_SPParameter, sO_LUONGParameter, gIA_NHAPParameter, tHANH_TIENParameter, gIAM_GIAParameter, mA_HDParameter);
        }
    
        public virtual int DELETE_HOA_DON(Nullable<int> mA_HD)
        {
            var mA_HDParameter = mA_HD.HasValue ?
                new ObjectParameter("MA_HD", mA_HD) :
                new ObjectParameter("MA_HD", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DELETE_HOA_DON", mA_HDParameter);
        }
    
        public virtual int DELETE_HOA_DON_NHAP(Nullable<int> mA_HD)
        {
            var mA_HDParameter = mA_HD.HasValue ?
                new ObjectParameter("MA_HD", mA_HD) :
                new ObjectParameter("MA_HD", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DELETE_HOA_DON_NHAP", mA_HDParameter);
        }
    
        public virtual int DELETE_NHAN_VIEN(string mANV)
        {
            var mANVParameter = mANV != null ?
                new ObjectParameter("MANV", mANV) :
                new ObjectParameter("MANV", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DELETE_NHAN_VIEN", mANVParameter);
        }
    
        public virtual ObjectResult<GET_ALL_DANH_MUC_DELETE_Result> GET_ALL_DANH_MUC_DELETE()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GET_ALL_DANH_MUC_DELETE_Result>("GET_ALL_DANH_MUC_DELETE");
        }
    
        public virtual ObjectResult<GET_ALL_DANH_MUC_TON_TAI_Result> GET_ALL_DANH_MUC_TON_TAI()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GET_ALL_DANH_MUC_TON_TAI_Result>("GET_ALL_DANH_MUC_TON_TAI");
        }
    
        public virtual ObjectResult<GET_ALL_KHACHHANG_Result> GET_ALL_KHACHHANG()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GET_ALL_KHACHHANG_Result>("GET_ALL_KHACHHANG");
        }
    
        public virtual ObjectResult<GET_ALL_NHAN_VIEN_Result> GET_ALL_NHAN_VIEN()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GET_ALL_NHAN_VIEN_Result>("GET_ALL_NHAN_VIEN");
        }
    
        public virtual ObjectResult<GET_ALL_SAN_PHAM_Result> GET_ALL_SAN_PHAM()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GET_ALL_SAN_PHAM_Result>("GET_ALL_SAN_PHAM");
        }
    
        public virtual ObjectResult<GETALLCTHD_BAN_Result> GETALLCTHD_BAN(Nullable<int> ma_hd)
        {
            var ma_hdParameter = ma_hd.HasValue ?
                new ObjectParameter("ma_hd", ma_hd) :
                new ObjectParameter("ma_hd", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GETALLCTHD_BAN_Result>("GETALLCTHD_BAN", ma_hdParameter);
        }
    
        public virtual ObjectResult<GETALLCTHD_NHAP_Result> GETALLCTHD_NHAP(Nullable<int> ma_hd)
        {
            var ma_hdParameter = ma_hd.HasValue ?
                new ObjectParameter("ma_hd", ma_hd) :
                new ObjectParameter("ma_hd", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GETALLCTHD_NHAP_Result>("GETALLCTHD_NHAP", ma_hdParameter);
        }
    
        public virtual ObjectResult<GETALLHOADON_Result> GETALLHOADON(string nv)
        {
            var nvParameter = nv != null ?
                new ObjectParameter("nv", nv) :
                new ObjectParameter("nv", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GETALLHOADON_Result>("GETALLHOADON", nvParameter);
        }
    
        public virtual ObjectResult<GETALLHOADONNHAP_Result> GETALLHOADONNHAP(string manv)
        {
            var manvParameter = manv != null ?
                new ObjectParameter("manv", manv) :
                new ObjectParameter("manv", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GETALLHOADONNHAP_Result>("GETALLHOADONNHAP", manvParameter);
        }
    
        public virtual ObjectResult<LOC_HOA_DON_Result> LOC_HOA_DON(string manv, Nullable<System.DateTime> sTART, Nullable<System.DateTime> eND)
        {
            var manvParameter = manv != null ?
                new ObjectParameter("manv", manv) :
                new ObjectParameter("manv", typeof(string));
    
            var sTARTParameter = sTART.HasValue ?
                new ObjectParameter("START", sTART) :
                new ObjectParameter("START", typeof(System.DateTime));
    
            var eNDParameter = eND.HasValue ?
                new ObjectParameter("END", eND) :
                new ObjectParameter("END", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<LOC_HOA_DON_Result>("LOC_HOA_DON", manvParameter, sTARTParameter, eNDParameter);
        }
    
        public virtual ObjectResult<LOC_HOA_DON_NHAP_Result> LOC_HOA_DON_NHAP(string mANV, Nullable<System.DateTime> sTART, Nullable<System.DateTime> eND)
        {
            var mANVParameter = mANV != null ?
                new ObjectParameter("MANV", mANV) :
                new ObjectParameter("MANV", typeof(string));
    
            var sTARTParameter = sTART.HasValue ?
                new ObjectParameter("START", sTART) :
                new ObjectParameter("START", typeof(System.DateTime));
    
            var eNDParameter = eND.HasValue ?
                new ObjectParameter("END", eND) :
                new ObjectParameter("END", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<LOC_HOA_DON_NHAP_Result>("LOC_HOA_DON_NHAP", mANVParameter, sTARTParameter, eNDParameter);
        }
    
        public virtual int PRD_INSERT_CTHD(string mA_SP, Nullable<int> sO_LUONG, Nullable<double> gIA_BAN, Nullable<double> tHANH_TIEN, Nullable<double> gIAM_GIA, Nullable<int> mA_HD)
        {
            var mA_SPParameter = mA_SP != null ?
                new ObjectParameter("MA_SP", mA_SP) :
                new ObjectParameter("MA_SP", typeof(string));
    
            var sO_LUONGParameter = sO_LUONG.HasValue ?
                new ObjectParameter("SO_LUONG", sO_LUONG) :
                new ObjectParameter("SO_LUONG", typeof(int));
    
            var gIA_BANParameter = gIA_BAN.HasValue ?
                new ObjectParameter("GIA_BAN", gIA_BAN) :
                new ObjectParameter("GIA_BAN", typeof(double));
    
            var tHANH_TIENParameter = tHANH_TIEN.HasValue ?
                new ObjectParameter("THANH_TIEN", tHANH_TIEN) :
                new ObjectParameter("THANH_TIEN", typeof(double));
    
            var gIAM_GIAParameter = gIAM_GIA.HasValue ?
                new ObjectParameter("GIAM_GIA", gIAM_GIA) :
                new ObjectParameter("GIAM_GIA", typeof(double));
    
            var mA_HDParameter = mA_HD.HasValue ?
                new ObjectParameter("MA_HD", mA_HD) :
                new ObjectParameter("MA_HD", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PRD_INSERT_CTHD", mA_SPParameter, sO_LUONGParameter, gIA_BANParameter, tHANH_TIENParameter, gIAM_GIAParameter, mA_HDParameter);
        }
    
        public virtual ObjectResult<SEARCH_DANH_MUC_DELETE_Result> SEARCH_DANH_MUC_DELETE(string mA_DM, string tEN_DM, string mO_TA)
        {
            var mA_DMParameter = mA_DM != null ?
                new ObjectParameter("MA_DM", mA_DM) :
                new ObjectParameter("MA_DM", typeof(string));
    
            var tEN_DMParameter = tEN_DM != null ?
                new ObjectParameter("TEN_DM", tEN_DM) :
                new ObjectParameter("TEN_DM", typeof(string));
    
            var mO_TAParameter = mO_TA != null ?
                new ObjectParameter("MO_TA", mO_TA) :
                new ObjectParameter("MO_TA", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SEARCH_DANH_MUC_DELETE_Result>("SEARCH_DANH_MUC_DELETE", mA_DMParameter, tEN_DMParameter, mO_TAParameter);
        }
    
        public virtual ObjectResult<SEARCH_DANH_MUC_TON_TAI_Result> SEARCH_DANH_MUC_TON_TAI(string mA_DM, string tEN_DM, string mO_TA)
        {
            var mA_DMParameter = mA_DM != null ?
                new ObjectParameter("MA_DM", mA_DM) :
                new ObjectParameter("MA_DM", typeof(string));
    
            var tEN_DMParameter = tEN_DM != null ?
                new ObjectParameter("TEN_DM", tEN_DM) :
                new ObjectParameter("TEN_DM", typeof(string));
    
            var mO_TAParameter = mO_TA != null ?
                new ObjectParameter("MO_TA", mO_TA) :
                new ObjectParameter("MO_TA", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SEARCH_DANH_MUC_TON_TAI_Result>("SEARCH_DANH_MUC_TON_TAI", mA_DMParameter, tEN_DMParameter, mO_TAParameter);
        }
    
        public virtual ObjectResult<SEARCH_HOA_DON_Result> SEARCH_HOA_DON(string mA_NV, string mA_HD)
        {
            var mA_NVParameter = mA_NV != null ?
                new ObjectParameter("MA_NV", mA_NV) :
                new ObjectParameter("MA_NV", typeof(string));
    
            var mA_HDParameter = mA_HD != null ?
                new ObjectParameter("MA_HD", mA_HD) :
                new ObjectParameter("MA_HD", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SEARCH_HOA_DON_Result>("SEARCH_HOA_DON", mA_NVParameter, mA_HDParameter);
        }
    
        public virtual ObjectResult<SEARCH_HOA_DON_NHAP_Result> SEARCH_HOA_DON_NHAP(string ma_hd, string manv)
        {
            var ma_hdParameter = ma_hd != null ?
                new ObjectParameter("ma_hd", ma_hd) :
                new ObjectParameter("ma_hd", typeof(string));
    
            var manvParameter = manv != null ?
                new ObjectParameter("manv", manv) :
                new ObjectParameter("manv", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SEARCH_HOA_DON_NHAP_Result>("SEARCH_HOA_DON_NHAP", ma_hdParameter, manvParameter);
        }
    
        public virtual ObjectResult<SEARCH_KHACH_HANG_Result> SEARCH_KHACH_HANG(string mA_KH, string tEN_KH, string sDT, string dIA_CHI)
        {
            var mA_KHParameter = mA_KH != null ?
                new ObjectParameter("MA_KH", mA_KH) :
                new ObjectParameter("MA_KH", typeof(string));
    
            var tEN_KHParameter = tEN_KH != null ?
                new ObjectParameter("TEN_KH", tEN_KH) :
                new ObjectParameter("TEN_KH", typeof(string));
    
            var sDTParameter = sDT != null ?
                new ObjectParameter("SDT", sDT) :
                new ObjectParameter("SDT", typeof(string));
    
            var dIA_CHIParameter = dIA_CHI != null ?
                new ObjectParameter("DIA_CHI", dIA_CHI) :
                new ObjectParameter("DIA_CHI", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SEARCH_KHACH_HANG_Result>("SEARCH_KHACH_HANG", mA_KHParameter, tEN_KHParameter, sDTParameter, dIA_CHIParameter);
        }
    
        public virtual ObjectResult<SEARCH_NHAN_VIEN_Result> SEARCH_NHAN_VIEN(string mA_NV, string tEN_NV, string sDT, string nGAY_VL, string dIA_CHI, string gIOI_TINH, string eMAIL, string tAI_KHOAN, string cHUC_VU)
        {
            var mA_NVParameter = mA_NV != null ?
                new ObjectParameter("MA_NV", mA_NV) :
                new ObjectParameter("MA_NV", typeof(string));
    
            var tEN_NVParameter = tEN_NV != null ?
                new ObjectParameter("TEN_NV", tEN_NV) :
                new ObjectParameter("TEN_NV", typeof(string));
    
            var sDTParameter = sDT != null ?
                new ObjectParameter("SDT", sDT) :
                new ObjectParameter("SDT", typeof(string));
    
            var nGAY_VLParameter = nGAY_VL != null ?
                new ObjectParameter("NGAY_VL", nGAY_VL) :
                new ObjectParameter("NGAY_VL", typeof(string));
    
            var dIA_CHIParameter = dIA_CHI != null ?
                new ObjectParameter("DIA_CHI", dIA_CHI) :
                new ObjectParameter("DIA_CHI", typeof(string));
    
            var gIOI_TINHParameter = gIOI_TINH != null ?
                new ObjectParameter("GIOI_TINH", gIOI_TINH) :
                new ObjectParameter("GIOI_TINH", typeof(string));
    
            var eMAILParameter = eMAIL != null ?
                new ObjectParameter("EMAIL", eMAIL) :
                new ObjectParameter("EMAIL", typeof(string));
    
            var tAI_KHOANParameter = tAI_KHOAN != null ?
                new ObjectParameter("TAI_KHOAN", tAI_KHOAN) :
                new ObjectParameter("TAI_KHOAN", typeof(string));
    
            var cHUC_VUParameter = cHUC_VU != null ?
                new ObjectParameter("CHUC_VU", cHUC_VU) :
                new ObjectParameter("CHUC_VU", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SEARCH_NHAN_VIEN_Result>("SEARCH_NHAN_VIEN", mA_NVParameter, tEN_NVParameter, sDTParameter, nGAY_VLParameter, dIA_CHIParameter, gIOI_TINHParameter, eMAILParameter, tAI_KHOANParameter, cHUC_VUParameter);
        }
    
        public virtual ObjectResult<SEARCH_SAN_PHAM_Result> SEARCH_SAN_PHAM(string mA_SP, string tEN_SP, string gIA_NHAP, string gIA_BAN, string sO_LUONG, string gIAM_GIA, string gHI_CHU, string mA_DM)
        {
            var mA_SPParameter = mA_SP != null ?
                new ObjectParameter("MA_SP", mA_SP) :
                new ObjectParameter("MA_SP", typeof(string));
    
            var tEN_SPParameter = tEN_SP != null ?
                new ObjectParameter("TEN_SP", tEN_SP) :
                new ObjectParameter("TEN_SP", typeof(string));
    
            var gIA_NHAPParameter = gIA_NHAP != null ?
                new ObjectParameter("GIA_NHAP", gIA_NHAP) :
                new ObjectParameter("GIA_NHAP", typeof(string));
    
            var gIA_BANParameter = gIA_BAN != null ?
                new ObjectParameter("GIA_BAN", gIA_BAN) :
                new ObjectParameter("GIA_BAN", typeof(string));
    
            var sO_LUONGParameter = sO_LUONG != null ?
                new ObjectParameter("SO_LUONG", sO_LUONG) :
                new ObjectParameter("SO_LUONG", typeof(string));
    
            var gIAM_GIAParameter = gIAM_GIA != null ?
                new ObjectParameter("GIAM_GIA", gIAM_GIA) :
                new ObjectParameter("GIAM_GIA", typeof(string));
    
            var gHI_CHUParameter = gHI_CHU != null ?
                new ObjectParameter("GHI_CHU", gHI_CHU) :
                new ObjectParameter("GHI_CHU", typeof(string));
    
            var mA_DMParameter = mA_DM != null ?
                new ObjectParameter("MA_DM", mA_DM) :
                new ObjectParameter("MA_DM", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SEARCH_SAN_PHAM_Result>("SEARCH_SAN_PHAM", mA_SPParameter, tEN_SPParameter, gIA_NHAPParameter, gIA_BANParameter, sO_LUONGParameter, gIAM_GIAParameter, gHI_CHUParameter, mA_DMParameter);
        }
    
        public virtual int sp_alterdiagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_alterdiagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_creatediagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_creatediagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_dropdiagram(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_dropdiagram", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagramdefinition_Result> sp_helpdiagramdefinition(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagramdefinition_Result>("sp_helpdiagramdefinition", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagrams_Result> sp_helpdiagrams(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagrams_Result>("sp_helpdiagrams", diagramnameParameter, owner_idParameter);
        }
    
        public virtual int sp_renamediagram(string diagramname, Nullable<int> owner_id, string new_diagramname)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var new_diagramnameParameter = new_diagramname != null ?
                new ObjectParameter("new_diagramname", new_diagramname) :
                new ObjectParameter("new_diagramname", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_renamediagram", diagramnameParameter, owner_idParameter, new_diagramnameParameter);
        }
    
        public virtual int sp_upgraddiagrams()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_upgraddiagrams");
        }
    
        public virtual ObjectResult<THONG_KE_SAN_PHAM_BAN_CHAY_Result> THONG_KE_SAN_PHAM_BAN_CHAY(string nGAY, string tHANG, string nAM, string mA_SP)
        {
            var nGAYParameter = nGAY != null ?
                new ObjectParameter("NGAY", nGAY) :
                new ObjectParameter("NGAY", typeof(string));
    
            var tHANGParameter = tHANG != null ?
                new ObjectParameter("THANG", tHANG) :
                new ObjectParameter("THANG", typeof(string));
    
            var nAMParameter = nAM != null ?
                new ObjectParameter("NAM", nAM) :
                new ObjectParameter("NAM", typeof(string));
    
            var mA_SPParameter = mA_SP != null ?
                new ObjectParameter("MA_SP", mA_SP) :
                new ObjectParameter("MA_SP", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<THONG_KE_SAN_PHAM_BAN_CHAY_Result>("THONG_KE_SAN_PHAM_BAN_CHAY", nGAYParameter, tHANGParameter, nAMParameter, mA_SPParameter);
        }
    
        public virtual ObjectResult<THONG_KE_SAN_PHAM_NHAP_Result> THONG_KE_SAN_PHAM_NHAP(string nGAY, string tHANG, string nAM, string mA_SP)
        {
            var nGAYParameter = nGAY != null ?
                new ObjectParameter("NGAY", nGAY) :
                new ObjectParameter("NGAY", typeof(string));
    
            var tHANGParameter = tHANG != null ?
                new ObjectParameter("THANG", tHANG) :
                new ObjectParameter("THANG", typeof(string));
    
            var nAMParameter = nAM != null ?
                new ObjectParameter("NAM", nAM) :
                new ObjectParameter("NAM", typeof(string));
    
            var mA_SPParameter = mA_SP != null ?
                new ObjectParameter("MA_SP", mA_SP) :
                new ObjectParameter("MA_SP", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<THONG_KE_SAN_PHAM_NHAP_Result>("THONG_KE_SAN_PHAM_NHAP", nGAYParameter, tHANGParameter, nAMParameter, mA_SPParameter);
        }
    
        public virtual ObjectResult<THONG_KE_SAN_PHAM_TON_Result> THONG_KE_SAN_PHAM_TON()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<THONG_KE_SAN_PHAM_TON_Result>("THONG_KE_SAN_PHAM_TON");
        }
    
        public virtual int UPDATE_SO_LUONG_SAN_PHAM(string mASP, Nullable<int> sL)
        {
            var mASPParameter = mASP != null ?
                new ObjectParameter("MASP", mASP) :
                new ObjectParameter("MASP", typeof(string));
    
            var sLParameter = sL.HasValue ?
                new ObjectParameter("SL", sL) :
                new ObjectParameter("SL", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UPDATE_SO_LUONG_SAN_PHAM", mASPParameter, sLParameter);
        }
    }
}
