//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class SAN_PHAM
    {
        public string MA_SP { get; set; }
        public string TEN_SP { get; set; }
        public double GIA_NHAP { get; set; }
        public double GIA_BAN { get; set; }
        public Nullable<int> SO_LUONG { get; set; }
        public Nullable<int> GIAM_GIA { get; set; }
        public string GHI_CHU { get; set; }
        public string MA_DM { get; set; }
        public Nullable<byte> TRANG_THAI { get; set; }
    
        public virtual DANH_MUC DANH_MUC { get; set; }
    }
}
